export interface ServiceData {
  slug: string;
  num: string;
  title: string;
  tagline: string;
  heroImg: string;
  cardImg: string;
  overview: string;
  paragraphs: string[];
  inclusions: string[];
  features: { icon: string; title: string; desc: string }[];
  faqs: { q: string; a: string }[];
  testimonialIndices: number[];
}

export const SERVICES_DATA: ServiceData[] = [
  {
    slug: 'residential-design',
    num: '01',
    title: 'Residential Design',
    tagline: 'From your first sketch to your council-approved design — all under one roof.',
    heroImg: 'https://cdn.builder.io/api/v1/image/assets%2F0df748b9b86d4bc5af1be6fda4f6f0d0%2F6049763deb68490486b31b8246cd37d6?format=webp&width=1600',
    cardImg: 'https://cdn.builder.io/api/v1/image/assets%2F0df748b9b86d4bc5af1be6fda4f6f0d0%2F6049763deb68490486b31b8246cd37d6?format=webp&width=700',
    overview: 'Full home design — from concept to council — for new builds across the Perth metropolitan area.',
    paragraphs: [
      'Building a new home is one of the most significant decisions you\'ll ever make. Getting the design right from the start saves money, time, and frustration. At Patrick De Rossi Design & Drafting, we work with you from the very first conversation through to a complete, council-ready drawing package.',
      'Every residential design begins with understanding how you live. Your block, your lifestyle, your budget, and your vision — these four things drive every decision we make. We listen first, design second.',
      'With 17+ years designing homes across Perth\'s diverse suburbs, we have the local R-Code knowledge to make sure your design not only looks exceptional but meets every requirement first time. No back-and-forth with council. No costly redesigns. Just a smooth, efficient path from concept to permit.',
    ],
    inclusions: [
      'Initial consultation and design brief',
      'Site analysis and orientation study',
      'Concept floor plans (2 design options)',
      'Elevations — all four aspects',
      'Site plan and north point',
      'Colour and material schedule',
      'Energy efficiency report (NatHERS)',
      'Development Application (DA) if required',
      'Council liaison and query management',
      'Final signed drawing set for permit',
    ],
    features: [
      { icon: '◎', title: 'R-Code Compliant', desc: 'Every design is checked against WA Residential Design Codes, WAPC policy and your local authority\'s scheme before lodgement.' },
      { icon: '◈', title: 'Two Concept Options', desc: 'We develop two distinct concept directions so you can choose the layout that best suits your block and lifestyle — then refine from there.' },
      { icon: '⬡', title: 'Energy Efficiency', desc: 'NatHERS energy assessments included. We design with passive solar principles to reduce your long-term energy costs.' },
      { icon: '◇', title: '3D Visualisation', desc: 'Optional 3D renders available so you can walk through your home before a single brick is laid.' },
      { icon: '◐', title: 'Council Management', desc: 'We manage the Development Application and all council correspondence from lodgement through to approval on your behalf.' },
      { icon: '⬟', title: 'Builder-Ready Plans', desc: 'Our drawing sets are consistently praised by builders for their clarity and completeness. Less confusion on site means fewer variations.' },
    ],
    faqs: [
      { q: 'How long does residential design take?', a: 'From initial consultation to a council-ready drawing set typically takes 8–14 weeks, depending on council assessment times and the complexity of your project. We will give you a realistic timeline at quote stage.' },
      { q: 'Do I need a Development Application (DA)?', a: 'Not always. Many residential designs can proceed under Deemed-to-Comply provisions of the R-Codes and don\'t require a full DA. We assess your specific block and design against your local planning scheme and advise you accordingly from day one.' },
      { q: 'Can you design on any block size or shape?', a: 'Yes. We regularly work on battle-axe blocks, narrow lots (from 8m wide), corner sites, sloping sites, and large rural-residential properties across greater Perth.' },
      { q: 'What if I only have a rough idea of what I want?', a: 'That\'s completely fine — most clients come to us with a general brief rather than a finished design. Our consultation process is specifically designed to help you develop and refine your vision into a clear design brief we can work from.' },
    ],
    testimonialIndices: [2, 3],
  },
  {
    slug: 'construction-drawings',
    num: '02',
    title: 'Construction Drawings',
    tagline: 'Comprehensive working drawings that give builders everything they need to build with confidence.',
    heroImg: '/svc-construction-plans.jpg',
    cardImg: '/svc-construction-plans.jpg',
    overview: 'Detailed construction documentation sets covering every technical requirement for permit and on-site use.',
    paragraphs: [
      'Great architecture only becomes reality through great documentation. Our construction drawing packages are built to the standard that builders, certifiers, and local authorities need — so your project moves from approval to on-site start without unnecessary delays.',
      'We produce full working drawing sets that cover every discipline your certifier and builder require. Coordinated, accurate, and complete from the outset — because discovering a missing detail at permit stage costs everyone time and money.',
      'Our drawings are consistently singled out by builders for their clarity. When the documentation is right, there are fewer RFIs, fewer variations, and a smoother construction process for everyone on the project.',
    ],
    inclusions: [
      'Detailed floor plans at 1:100 and 1:50',
      'Full elevations — all four aspects',
      'Cross-sections and wall sections',
      'Roof plan with drainage direction',
      'Site plan with setbacks and easements',
      'Electrical and wet area layouts',
      'Window and door schedule',
      'Structural notes and footing detail',
      'Stormwater concept plan',
      'Certificate of Design Compliance (CDC)',
    ],
    features: [
      { icon: '◎', title: 'Certifier-Ready', desc: 'Every set is produced to satisfy your building certifier\'s requirements and NCC compliance — including required structural and energy details.' },
      { icon: '◈', title: 'Multi-Scale Plans', desc: 'We produce drawings at the scales required for different disciplines — 1:200 for context, 1:100 for planning, 1:50 for construction details.' },
      { icon: '⬡', title: 'Wet Area Compliance', desc: 'Bathroom, kitchen, and laundry details are drawn to AS 3740 waterproofing requirements so your certifier has everything they need.' },
      { icon: '◇', title: 'Stormwater Design', desc: 'Stormwater concept plans included showing disposal path, soakwells (where applicable) and compliance with WAPC guidelines.' },
      { icon: '◐', title: 'Coordinated Set', desc: 'All drawings are fully coordinated — architectural, structural, and services — so builders get a unified picture of the finished project.' },
      { icon: '⬟', title: 'Digital + Hard Copy', desc: 'Full resolution PDF sets and A1/A3 print-ready files provided. DXF/DWG available on request for builder take-offs.' },
    ],
    faqs: [
      { q: 'What\'s the difference between planning drawings and construction drawings?', a: 'Planning drawings (used for DA approval) are less detailed and focus on spatial relationships and R-Code compliance. Construction drawings go much further — they include the technical detail your builder and certifier need to actually build and certify the structure.' },
      { q: 'Do I need an engineer as well?', a: 'For most residential projects in WA, a structural engineer is required to design footings and any significant steel or timber elements. We coordinate directly with your engineer and incorporate their details into our drawing set at no extra cost to you.' },
      { q: 'Can you take over documentation from another designer?', a: 'Yes. If you have existing plans at concept stage or even partially documented, we can take these on, review them, and complete the construction documentation to our standard.' },
      { q: 'How long does a full documentation set take to produce?', a: 'A complete working drawing set for a standard residential project typically takes 3–5 weeks from confirmed design brief. More complex projects or projects requiring extensive structural coordination may take longer — we will advise at quote stage.' },
    ],
    testimonialIndices: [2, 5],
  },
  {
    slug: 'multi-unit-development',
    num: '03',
    title: 'Multi-Unit Development',
    tagline: 'Maximise your site\'s potential with design that works hard on every square metre.',
    heroImg: '/svc-multi-unit.jpg',
    cardImg: '/svc-multi-unit.jpg',
    overview: 'Duplex, triplex, grouped dwelling and apartment design that extracts full development value from your site.',
    paragraphs: [
      'Perth\'s changing residential density codes have opened up significant development potential across the metro area. Getting the design and approvals right is the difference between a project that delivers its expected return and one that doesn\'t.',
      'We specialise in multi-unit residential developments across the full density spectrum — from Duplexes and R40 grouped dwellings to R80 apartments. Our depth of knowledge in WAPC policy, local planning schemes and R-Code dual-density calculations means your development potential is accurately assessed from day one.',
      'We work with both owner-occupiers looking to add a second dwelling and experienced developers seeking yield-optimised design that still meets all planning and liveability requirements. Our track record across Perth\'s most active development corridors speaks for itself.',
    ],
    inclusions: [
      'Development potential assessment and advice',
      'Survey coordination and lot yield calculation',
      'Concept planning — all dwelling options',
      'R-Code dual density analysis',
      'WAPC and local scheme compliance check',
      'Development Application preparation and lodgement',
      'Council and WAPC liaison',
      'Full working drawings for all dwellings',
      'Stormwater and servicing concept',
      'Subdivision plan coordination (where applicable)',
    ],
    features: [
      { icon: '◎', title: 'Yield Optimisation', desc: 'We assess your block\'s full development potential under current R-Codes before committing to a design — ensuring you don\'t leave dwellings on the table.' },
      { icon: '◈', title: 'WAPC Experience', desc: 'Extensive experience with WAPC-assessed applications, including Structure Plan areas, METRONET precincts and infill development sites.' },
      { icon: '⬡', title: 'Council Relationships', desc: 'Established relationships with planning officers across Perth\'s metro councils mean pre-application meetings are productive and approvals are smoother.' },
      { icon: '◇', title: 'Liveable Design', desc: 'Development yield and liveable design aren\'t mutually exclusive. Every dwelling is designed to meet or exceed the liveability provisions of the R-Codes.' },
      { icon: '◐', title: 'Investor Focused', desc: 'We understand investment drivers. Our designs balance construction efficiency with rental appeal — the right mix for your target market.' },
      { icon: '⬟', title: 'Subdivision Ready', desc: 'Where subdivision is the goal, we coordinate with your surveyor to ensure the design facilitates a clean, straightforward survey strata or green title subdivision.' },
    ],
    faqs: [
      { q: 'How do I know if my block can be developed?', a: 'Your block\'s development potential depends on its R-Code zoning, size, dimensions, and local scheme provisions. We offer a free initial assessment to advise you on what\'s achievable before you commit to any fees.' },
      { q: 'What\'s the difference between a duplex and grouped dwelling?', a: 'A duplex involves two dwellings on a single lot, typically designed for green-title or survey-strata subdivision. Grouped dwellings are a class of residential development under the R-Codes that allows more than two dwellings on a single lot under certain zoning conditions. We can explain which applies to your site.' },
      { q: 'Do I need WAPC approval for my development?', a: 'It depends on the number of dwellings and your local authority\'s assessment responsibilities. Some developments are assessed by the local council, others require WAPC involvement. We identify the correct approval pathway for your specific project from the outset.' },
      { q: 'Can I build a duplex and still live in one of the dwellings?', a: 'Absolutely. Many of our clients develop a second dwelling at the rear of their existing property to retain as a rental, or build a duplex pair where they occupy one and sell or rent the other. We design for both scenarios.' },
    ],
    testimonialIndices: [1, 4],
  },
  {
    slug: 'renovation-extension',
    num: '04',
    title: 'Renovation & Extension',
    tagline: 'More space, better flow, and a home that works harder — without the cost of starting over.',
    heroImg: '/svc-renovations.jpg',
    cardImg: '/svc-renovations.jpg',
    overview: 'Thoughtful alterations and additions that respect your home\'s character while delivering the space you need.',
    paragraphs: [
      'Your existing home has something a new build can\'t offer: character, a mature garden, a neighbourhood you already love. A well-designed renovation or extension works with all of that — delivering the space and functionality you need without sacrificing what makes your home special.',
      'Renovations and extensions carry their own unique challenges. Matching existing materials, working with legacy structure, managing the boundary between old and new — these are design problems we solve every day. Our experience across Perth\'s full range of housing stock means we\'ve seen it all.',
      'Whether you\'re adding a rear extension to create an open-plan living zone, converting your garage, adding a second storey, or reconfiguring the internal layout, we develop a design that solves your specific brief — and we handle every step of the approval process.',
    ],
    inclusions: [
      'Existing conditions survey and as-built drawings',
      'Design brief consultation',
      'Concept plans and elevations for the extension/alteration',
      'Existing/proposed comparison drawings for council',
      'R-Code and local scheme compliance check',
      'Building Permit application preparation',
      'Council liaison and query management',
      'Full working drawings for construction',
      'Structural coordination with engineer',
      'Energy compliance (Section J/NatHERS where required)',
    ],
    features: [
      { icon: '◎', title: 'As-Built Survey', desc: 'We measure and document your existing home before designing the extension — ensuring the new work integrates seamlessly with the existing structure and services.' },
      { icon: '◈', title: 'Heritage Sensitivity', desc: 'Experienced in additions to pre-war and heritage-listed properties. We design additions that respect the original character and satisfy Heritage Council requirements.' },
      { icon: '⬡', title: 'Second Storey Additions', desc: 'Second storey additions require careful structural and planning consideration. We have extensive experience designing additions that work both aesthetically and structurally.' },
      { icon: '◇', title: 'Garage Conversions', desc: 'Converting a garage into a habitable room involves specific compliance requirements. We handle every aspect of the design and approval process for you.' },
      { icon: '◐', title: 'Seamless Integration', desc: 'The junction between old and new is where renovations succeed or fail. We design roof forms, ceiling heights, and floor levels that create a unified home, not a patchwork.' },
      { icon: '⬟', title: 'Live-In Friendly', desc: 'We understand that many renovation projects are staged to allow clients to remain in the home during construction. Our documentation supports staged works wherever possible.' },
    ],
    faqs: [
      { q: 'Do I need council approval for a house extension?', a: 'In most cases, yes. Extensions that increase the footprint of your home typically require a Building Permit, and depending on the scale, may also require a Development Application. We advise you on the exact requirements for your specific project and property.' },
      { q: 'Can you work from my builder\'s rough sketches?', a: 'Yes, we work from client-supplied sketch briefs, napkin sketches, and ideas boards regularly. Our job is to translate your ideas into a design that works functionally, aesthetically, and within the planning framework.' },
      { q: 'My house is pre-1940 — are there special rules?', a: 'Possibly. Some pre-1940 homes in Perth are individually heritage-listed or located within heritage-designated areas, which affects what alterations and additions require additional approval. We check heritage status as part of our initial assessment of every project.' },
      { q: 'How much does an extension cost to design?', a: 'Our fees for renovation and extension projects depend on the scope and complexity of the work — a small rear extension will be significantly less than a full second-storey addition. We provide a fixed, itemised quote before any work begins so there are no surprises.' },
    ],
    testimonialIndices: [0, 6],
  },
  {
    slug: 'granny-flats',
    num: '05',
    title: 'Granny Flats',
    tagline: 'Smart ancillary dwellings that maximise your block\'s potential within Perth\'s R-Code framework.',
    heroImg: '/svc-granny-flat.jpg',
    cardImg: '/svc-granny-flat.jpg',
    overview: 'Ancillary dwelling design for family accommodation or additional rental income, delivered permit-ready.',
    paragraphs: [
      'Granny flats — formally known as ancillary dwellings under WA\'s R-Codes — are one of Perth\'s most popular ways to maximise residential land value. Whether you\'re accommodating ageing parents, adult children, or creating a rental income stream, the design and compliance process needs to be handled correctly from the start.',
      'WA\'s R-Codes set specific rules for ancillary dwellings: maximum floor area, setbacks, parking, and the relationship between the ancillary and primary dwelling all need to satisfy specific provisions. We know these rules intimately and design to maximise liveable space within them every time.',
      'Our granny flat designs are compact but genuinely liveable — not afterthoughts. Every square metre is carefully planned to deliver a comfortable, functional home within the R-Code allowable envelope. Our approval track record with councils across Perth reflects the care we put into every submission.',
    ],
    inclusions: [
      'R-Code ancillary dwelling compliance assessment',
      'Concept floor plan and elevation design',
      'Site plan showing primary and ancillary dwellings',
      'Setback, open space and parking calculations',
      'Building Permit application preparation',
      'Council query management',
      'Full working drawings for construction',
      'Structural coordination',
      'Energy compliance report',
      'As-built drawings on completion (optional)',
    ],
    features: [
      { icon: '◎', title: 'R-Code Compliance', desc: 'Ancillary dwellings must satisfy specific R-Code provisions including maximum GFA (typically 60m²), setbacks, and parking. We design to the maximum allowable envelope every time.' },
      { icon: '◈', title: 'Permit Expertise', desc: 'Granny flat approvals involve both the primary and ancillary dwelling on a single lot. We handle the complete permit package so nothing is overlooked.' },
      { icon: '⬡', title: 'Privacy Design', desc: 'We carefully consider outlook, screening, and acoustic separation between the primary and ancillary dwelling to ensure both occupants\' privacy and comfort.' },
      { icon: '◇', title: 'Flexible Layouts', desc: 'Studio, one-bedroom, and two-bedroom ancillary dwelling layouts all available. We match the layout to your specific use case — family accommodation, Airbnb, or long-term rental.' },
      { icon: '◐', title: 'Servicing Coordination', desc: 'Connecting water, power, sewer, and stormwater to a new ancillary dwelling requires careful planning. We flag servicing requirements early so you can get utility quotes during the design phase.' },
      { icon: '⬟', title: 'Fast Turnaround', desc: 'Granny flat projects are typically simpler than new homes. We prioritise fast turnaround on concept approval and working drawings so you can get your builder on site sooner.' },
    ],
    faqs: [
      { q: 'How big can a granny flat be in WA?', a: 'Under the Residential Design Codes, the maximum gross floor area for an ancillary dwelling is 60m² unless the local planning scheme allows otherwise. Some councils have adopted policies that permit larger ancillary dwellings in specific zones. We check your specific zoning as part of our initial assessment.' },
      { q: 'Can I rent out a granny flat?', a: 'Yes. WA legislation was changed in 2019 to allow ancillary dwellings to be rented to anyone, not just family members. This makes granny flats a popular investment for Perth homeowners with suitable blocks.' },
      { q: 'Does my block need to be a certain size?', a: 'The minimum site area for a primary dwelling plus ancillary dwelling depends on your R-Code zoning. As a general guide, most R20-R40 lots of 600m² or more can accommodate a 60m² ancillary dwelling, but we will confirm the exact requirements for your specific block.' },
      { q: 'Can I build a granny flat at the front of my property?', a: 'Generally, ancillary dwellings must be located behind the primary dwelling\'s primary street setback line. However, there are variations depending on the lot configuration and local planning scheme provisions. We assess every site individually.' },
    ],
    testimonialIndices: [0, 7],
  },
  {
    slug: 'carports-alfrescos-sheds',
    num: '06',
    title: 'Carports, Alfrescos & Sheds',
    tagline: 'Permit-ready drawings for outbuildings and outdoor structures — done right, done fast.',
    heroImg: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1600&q=80',
    cardImg: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=700&q=80',
    overview: 'Compliant documentation for carports, alfresco areas, fencing, sheds, and other ancillary structures.',
    paragraphs: [
      'Building a carport, alfresco, shed, or substantial fence without the correct approval can result in expensive rectification orders from your local council. Our documentation service makes sure your builder can get on site with everything in order — no surprises.',
      'Ancillary structures might seem straightforward, but Perth\'s local planning schemes and the R-Codes impose specific setback, coverage, and height rules that vary across councils. We know the rules and prepare drawings that satisfy every requirement from the first submission.',
      'Our service is fast, efficient, and fixed-fee. You get a complete, permit-ready drawing package and we manage any council queries on your behalf — so you can focus on getting your project built.',
    ],
    inclusions: [
      'R-Code and local scheme compliance check',
      'Site plan showing proposed structure and setbacks',
      'Floor plan and elevations of proposed structure',
      'Roof framing plan (where required)',
      'Council application preparation',
      'Liaising with council on your behalf',
      'Building Permit documentation',
      'Fencing height and sightline compliance drawings',
    ],
    features: [
      { icon: '◎', title: 'Fast Turnaround', desc: 'Ancillary structure drawings are our fastest service. Standard carport or alfresco documentation can be produced within 5–7 business days of receiving site details.' },
      { icon: '◈', title: 'Fixed Fees', desc: 'Simple, transparent fixed fees for standard ancillary structures. No hourly billing, no surprises. Quote provided upfront before any work begins.' },
      { icon: '⬡', title: 'All Structure Types', desc: 'We document carports (attached and freestanding), alfresco entertainment areas, pergolas, garden sheds, workshops, fencing, and pool fencing.' },
      { icon: '◇', title: 'Council Knowledge', desc: 'Every Perth metro council has slightly different rules on setbacks, height, and coverage for ancillary structures. We know them and apply the right rules to your specific address.' },
      { icon: '◐', title: 'Heritage Areas', desc: 'Building in a heritage-designated area? We understand the additional requirements and produce drawings that satisfy Heritage Council guidelines alongside standard building permit requirements.' },
      { icon: '⬟', title: 'Builder Coordination', desc: 'We\'re happy to liaise directly with your builder on structural details, ensuring the drawings accurately reflect what they intend to construct and satisfy the certifier\'s requirements.' },
    ],
    faqs: [
      { q: 'Do I need a permit to build a carport in Perth?', a: 'In most cases, yes. Carports are exempt from requiring a building permit only if they fall within specific size limits (typically under 10m² in WA) and meet all setback requirements. In practice, most carports require a permit. We assess your specific situation and advise you before you commit.' },
      { q: 'What about a freestanding shed in the backyard?', a: 'Same principle applies — sheds under 10m² with a maximum height of 2.4m may be exempt, but anything larger generally requires a Building Permit. If your shed is in a heritage area, additional approval may be required regardless of size.' },
      { q: 'Can I build an alfresco without approval?', a: 'Open pergolas without a roof may be exempt under certain conditions, but an alfresco with a roof structure will almost always require a Building Permit and, depending on setbacks, may need a Development Application from your local council.' },
      { q: 'How long does council approval take for a simple carport?', a: 'Once we submit your application, most local authorities will assess a straightforward ancillary structure application within 10–25 business days, though timelines vary between councils. We keep you updated throughout the process and follow up promptly on any council queries.' },
    ],
    testimonialIndices: [0, 8],
  },
];
