// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/patrick-derossi/Website.tsx": () => import("../components/mockups/patrick-derossi/Website.tsx")
};
